deposit/urls.py
# -*- encoding: utf-8 -*-

# Dissemin: open access policy enforcement tool
# Copyright (C) 2014 Antonin Delpeuch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

from __future__ import unicode_literals

from deposit import views
from django.conf.urls import url

urlpatterns = [
        url(r'^deposit_paper/(?P<pk>\d+)/$',
            views.start_view, name='upload_paper'),
        url(r'^deposits$',
            views.list_deposits, name='list_deposits'),
        url(r'^ajax/submit-deposit-(?P<pk>\d+)$',
            views.submitDeposit, name='ajax-submitDeposit'),
        url(r'^ajax/get-metadata-form$',
            views.get_metadata_form, name='ajax-getMetadataForm'),
        url(r'^repository-preferences/(?P<pk>\d+)/$',
            views.edit_repo_preferences, name='edit-repo-preferences'),
        url(r'^preferences$',
            views.edit_global_preferences, name='edit-global-preferences'),
]

notification/urls.py
"""
At the moment, this module will load API urls only if restframework is available.
"""

from django.conf import settings

if 'rest_framework' in settings.INSTALLED_APPS:
    from rest_framework.routers import DefaultRouter
    from django.conf.urls import url, include
    from . import views

    router = DefaultRouter()
    router.register(r'inbox', views.InboxViewSet, base_name='inbox')

    urlpatterns = [
        url(r'^', include(router.urls))
    ]
else:
    urlpatterns = []

papers/urls.py
# -*- encoding: utf-8 -*-

# Dissemin: open access policy enforcement tool
# Copyright (C) 2014 Antonin Delpeuch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

from __future__ import unicode_literals

from django.conf.urls import include
from django.conf.urls import url
from papers import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        # Paper views
        url(r'^search/$', views.PaperSearchView.as_view(), name='search'),
        url(r'^r/(?P<researcher>\d+)/(?P<slug>[\w-]*)$',
            views.ResearcherView.as_view(), name='researcher'),
        url(r'^researcher/(?P<researcher>\d+)$',
            views.ResearcherView.as_view()),  # Deprecated URL
        url(r'^(?P<orcid>[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[X0-9])/$',
            views.ResearcherView.as_view(), name='researcher-by-orcid'),
        url(r'^my-profile', views.myProfileView, name='my-profile'),
        url(r'^paper/(?P<pk>\d+)/$', views.PaperView.as_view()),  # Deprecated URL
        url(r'^p/(?P<pk>\d+)/(?P<slug>[\w-]*)$',
            views.PaperView.as_view(), name='paper'),
        url(r'^(?P<doi>10\..*)', views.PaperView.as_view(), name='paper-doi'),
        url(r'^search/b/(?P<publisher>\d+)/(?P<slug>[\w-]*)$',
            views.PublisherPapersView.as_view(), name='publisher-papers'),
        url(r'^journal/(?P<journal>\d+)/$',
            views.JournalPapersView.as_view(), name='journal'),
        # Institution-specific views
        url(r'^department/(?P<pk>\d+)/$',
            views.DepartmentView.as_view(), name='department'),
        url(r'^search/department/(?P<pk>\d+)/$',
            views.DepartmentPapersView.as_view(), name='department-papers'),
        url(r'^institution/(?P<pk>\d+)/$',
            views.InstitutionView.as_view()), # Deprecated URL
        url(r'^i/(?P<pk>\d+)/(?P<slug>[\w-]*)$',
            views.InstitutionView.as_view(), name='institution'),
        url(r'^institutions$',
            views.InstitutionsMapView.as_view(), name='institutions-map'),
        # Tasks, AJAX
        url(r'^ajax/', include('papers.ajax')),
        url(r'^researcher/(?P<pk>\d+)/update/$',
            views.refetchResearcher, name='refetch-researcher'),
        # API
        url(r'^api/', include('papers.api')),
]

deposit/hal/models.py
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as __
from deposit.models import DepositPreferences


class HALDepositPreferences(DepositPreferences):
    on_behalf_of = models.CharField(max_length=128,
                null=True,
                blank=True,
                verbose_name=__('HAL username'),
                help_text=__('If set, deposits will be associated to this HAL account.'))

deposit/models.py
# -*- encoding: utf-8 -*-

# Dissemin: open access policy enforcement tool
# Copyright (C) 2014 Antonin Delpeuch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#


from __future__ import unicode_literals

from caching.base import CachingManager
from caching.base import CachingMixin
from deposit.registry import protocol_registry
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils.translation import ugettext_lazy as _
from papers.models import OaiSource
from papers.models import Paper
from papers.models import OaiRecord
from papers.models import UPLOAD_TYPE_CHOICES
from upload.models import UploadedPDF

DEPOSIT_STATUS_CHOICES = [
   ('failed', _('Failed')), # we failed to deposit the paper
   ('faked', _('Faked')), # the deposit was faked (for tests)
   ('pending', _('Pending publication')), # the deposit has been
    # submitted but is not publicly visible yet
   ('published', _('Published')), # the deposit is visible on the repo
   ('refused', _('Refused by the repository')),
   ('deleted', _('Deleted')), # deleted by the repository
   ]

class RepositoryManager(CachingManager):
    pass

class Repository(models.Model, CachingMixin):
    """
    This model stores the parameters for a particular repository.

    The `name`, `description`, `url` and `logo` fields are used in the
    user interface to present the repository.

    The `protocol` field should contain the name of a subclass of
    :class:`~deposit.protocol.RepositoryProtocol` which implements the API supported
    by the repository.
    Note that this subclass needs to be registered in the :data:`~deposit.registry.protocol_registry`
    in order to be available at runtime.

    The `api_key`, `username`, `password` and `endpoint` are parameters
    used by the protocol implementation to perform the deposit.

    """
    objects = RepositoryManager()

    #: Name
    name = models.CharField(max_length=64)
    #: Description
    description = models.TextField()
    #: URL of the homepage (ex: http://arxiv.org/ )
    url = models.URLField(max_length=256, null=True, blank=True)
    #: Logo
    logo = models.ImageField(upload_to='repository_logos/')

    #: The identifier of the interface (protocol) used for that repository
    protocol = models.CharField(max_length=32)
    #: The source with which the OaiRecords associated with the deposits are created
    oaisource = models.ForeignKey(OaiSource)

    #: The identifier of the account under which papers should be deposited
    username = models.CharField(max_length=64, null=True, blank=True)
    #: The password for that account
    password = models.CharField(max_length=128, null=True, blank=True)
    #: An API key required by the protocol
    api_key = models.CharField(max_length=256, null=True, blank=True)
    #: The API's endpoint
    endpoint = models.CharField(max_length=256, null=True, blank=True)

    #: Setting this to false forbids any deposit in this repository
    enabled = models.BooleanField(default=True)

    def get_implementation(self):
        """
        Creates an instance of the class corresponding to the protocol identifier,
        bound with this repository. If the class cannot be found
        in the :data:`~deposit.registry.protocol_registry`, `None` is returned.

        :returns: the class corresponding to the value of the `protocol` field.
        """
        cls = protocol_registry.get(self.protocol)
        if cls is None:
            print "Warning: protocol not found: "+unicode(self.protocol)
            return
        return cls(self)

    def protocol_for_deposit(self, paper, user):
        """
        Returns an instance of the protocol initialized for the given
        paper and user, if initialization succeeded.

        :returns: an instance of the protocol implementation, or `None`
            if the instance failed to initialize with the given paper and user.
        """
        if not self.enabled:
            return
        instance = self.get_implementation()
        if instance is None:
            return
        if instance.init_deposit(paper, user):
            return instance

    def __unicode__(self):
        """
        The unicode representation is just the name of the repository.
        """
        return self.name

    class Meta:
        verbose_name_plural = 'Repositories'


class DepositRecord(models.Model):
    """
    This model stores the results of a deposit initiated by the user,
    regardless of its success. Protocol implementers should not
    have to deal with this model directly, their interfaces should
    only manipulate :class:`~deposit.protocol.DepositResult` objects
    and :class:`~deposit.protocol.DepositError` exceptions, depending
    on the success of the deposit.
    """
    paper = models.ForeignKey(Paper)
    user = models.ForeignKey(User)

    repository = models.ForeignKey(Repository)

    request = models.TextField(null=True, blank=True)
    identifier = models.CharField(max_length=512, null=True, blank=True)
    oairecord = models.ForeignKey(OaiRecord, null=True, blank=True)
    date = models.DateTimeField(auto_now=True)  # deposit date
    upload_type = models.CharField(max_length=64,choices=UPLOAD_TYPE_CHOICES)
    status = models.CharField(max_length=64,choices=DEPOSIT_STATUS_CHOICES)
    additional_info = JSONField(null=True, blank=True)

    file = models.ForeignKey(UploadedPDF)

    class Meta:
        db_table = 'papers_depositrecord'

    def __unicode__(self):
        if self.identifier:
            return self.identifier
        else:
            return unicode(_('Deposit'))

    def __repr__(self):
        return '<DepositRecord %s>' % unicode(self.identifier)


class DepositPreferences(models.Model):
    """
    This is an abstract base model to be subclassed
    by repositories. It stores the preferences one user
    might have concerning a particular repository, such
    as default affiliation for HAL, default license, or
    things we want to fill in automatically for them.
    """
    class Meta:
        abstract = True

    #: The user for which these preferences are stored
    user = models.ForeignKey(User)
    #: The repository for which these preferences apply
    repository = models.ForeignKey(Repository)

    @classmethod
    def get_form_class(self):
        """
        This method should be reimplemented to return
        the form class to edit these deposit preferences.
        This is expected to be a ModelForm that get_form
        will be able to initialize with values from an
        existing instance.
        """
        raise NotImplementedError()

    def get_form(self):
        """
        This method should return the
        """
        raise NotImplementedError()


    def __repr__(self):
        return '<DepositPreferences, user %s, repo %s>' %(
                    unicode(self.user), unicode(self.repository))

class UserPreferences(models.Model):
    """
    Stores the user's global preferences,
    not the ones specific to a particular repository.
    """
    user = models.OneToOneField(User)
    # Email address
    email = models.EmailField(max_length=512, null=True, blank=True,
       help_text=_(
        'We will use this email address to notify you when your deposits are accepted.'
    ))
    # The preferred repository, set by the user
    preferred_repository = models.ForeignKey(Repository,
        null=True, blank=True,
        related_name='preferred_by',
        help_text=_('This repository will be used by default for your deposits.'))
    # The last repository used by this user
    last_repository = models.ForeignKey(Repository,
        null=True, blank=True,
        related_name='last_used_by')

    @classmethod
    def get_by_user(cls, user):
        """
        Returns a UserPreferences instance for a particular user
        """
        userprefs, _ = cls.objects.get_or_create(user=user)
        return userprefs

deposit/osf/models.py
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from deposit.models import DepositPreferences

class OSFDepositPreferences(DepositPreferences):
    on_behalf_of = models.CharField(max_length=128,
                null=True,
                blank=True,
                verbose_name=_('OSF identifier'),
                help_text=_('If set, your deposits will be associated to this OSF account. This identifier is a string of letters and numbers which can be found in your OSF public profile URL.'))

deposit/zenodo/models.py
# Create your models here.

deposit/hal/forms.py
# -*- encoding: utf-8 -*-

# Dissemin: open access policy enforcement tool
# Copyright (C) 2014 Antonin Delpeuch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

from __future__ import unicode_literals

from autocomplete.widgets import Select2
from deposit.forms import FormWithAbstract
from deposit.hal.metadata import HAL_TOPIC_CHOICES
from django import forms
from django.utils.translation import ugettext as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from deposit.hal.models import HALDepositPreferences

class AffiliationSelect2(Select2):
    autocomplete_function = 'select2-customTemplate'

class HALForm(FormWithAbstract):

    def __init__(self, paper, **kwargs):
        super(HALForm, self).__init__(paper, **kwargs)
        self.fields['depositing_author'].choices = enumerate(
            map(unicode, paper.authors))

    topic = forms.ChoiceField(
            label=_('Scientific field'),
            choices=HAL_TOPIC_CHOICES)

    depositing_author = forms.TypedChoiceField(
        required=True,
        label=_('Depositing author'),
        choices=[], # choices are initialized from the paper later on
        coerce=int, # values are indexes of authors
    )

    affiliation = forms.CharField(
        required=True,
        label=_('Affiliation'),
        widget=AffiliationSelect2(
            url='autocomplete_affiliations',
            attrs={
                #'data-html': 'true',
                'width': '100%',
            },
        )
    )

class HALPreferencesForm(forms.ModelForm):
    class Meta:
        model = HALDepositPreferences
        fields = ['on_behalf_of']

    def __init__(self, *args, **kwargs):
        super(HALPreferencesForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(
            Submit('submit', _('Save')),
        )

deposit/hal/views.py
# Create your views here.

deposit/zenodo/views.py
# Create your views here.

deposit/templates/deposit/deposits.html
{% extends "dissemin/skeleton.html" %}

{% load i18n %}


{% block extra_head %}
{% include 'statistics/headers.html' %}
{% endblock %}

{% block headTitle %}{% trans "My deposits" %}{% endblock %}

{% block content %}
<div id="fullPage">
<h2>{% trans "My deposits" %}</h2>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    {% for deposit in deposits %}
        {% with deposit.paper as paper %}
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="deposit-heading-{{ deposit.id }}">
            <span class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion"
                    href="#deposit-collapse-{{ deposit.id }}"
                    aria-expanded="false"
                    aria-controls="deposit-collapse-{{ deposit.id }}">
                "{{ paper }}" in <strong>{{ deposit.repository }}</strong>
                </a>
            </span>
            </div>
            <div id="deposit-collapse-{{ deposit.id }}"
class="panel-collapse collapse"
            role="tabpanel" aria-labelledby="deposit-heading-{{ deposit.id }}">

                <div class="panel-body no-padding">
                   <table class="table" style="margin-bottom: 0px">
                        <tr>
                            <td>{% trans "Paper" %}</td>
                            <td><a href="{{ paper.url }}">{{ paper }}</a></td> 
                        </tr>
                        <tr>
                            <td>{% trans "Repository" %}</td>
                            <td><a href="{{ deposit.repository.url }}" target="blank">{{ deposit.repository }}</td>
                        </tr>
                        <tr>
                            <td>{% trans "Deposit date" %}</td>
                            <td>{{ deposit.date }}</td> 
                        </tr>
                        <tr>
                            <td>{% trans "Deposit type" %}</td>
                            <td>{{ deposit.get_upload_type_display }}</td> 
                        </tr>
                        <tr>
                            <td>{% trans "Identifier" %}</td>
                            <td>{{ deposit.identifier }}</td>
                        </tr>
                        {% with deposit.oairecord as r %}
                        {% if r %}
                        <tr>
                            <td>{% trans "Meta URL" %}</td>
                            <td><a href="{{ r.splash_url }}">{{ r.splash_url }}</a></td>
                        </tr>
                        {% if r.pdf_url %}
                        <tr>
                            <td>{% trans "PDF URL" %}</td>
                            <td><a href="{{ r.pdf_url }}">{{ r.pdf_url }}</a></td>
                        </tr>
                        {% endif %}
                        {% endif %}
                        {% endwith %}
                        <tr>
                            <td>{% trans "Status" %}</td>
                            <td>{{ deposit.get_status_display }}</td>
                        </tr>
                        {% with deposit.additional_info as info %}
                        {% for i in info %}
                        <tr>
                            <td>{{ i.label }}</td>
                            <td>{{ i.value }}</td>
                        </tr>
                        {% endfor %}
                        {% endwith %}
                    </table>
                </div>
            </div>
        </div>
    {% endwith %}
    {% empty %}
        <p class="notFound">
        {% blocktrans trimmed %}
        You have not made any deposit via
        Dissemin. What are you waiting for?
        Liberate your papers today.
        {% endblocktrans %}
        </p>
    {% endfor %}
</div>
{% endblock %}

deposit/templates/deposit/global_preferences.html
{% extends "dissemin/skeleton.html" %}

{% load i18n %}
{% load crispy_forms_tags %}


{% block extra_head %}
{% include 'statistics/headers.html' %}
<!-- repository-specific JS and CSS -->
{{ preferences_form.media }}
{% endblock %}

{% block headTitle %}{% trans "Preferences" %}{% endblock %}

{% block content %}
<div id="fullPage">
{% include "deposit/preferences_nav.html" %}
 
<form method="POST" action="{% url 'edit-global-preferences' %}" id="repositoryPreferencesForm">
	{% crispy preferences_form  %}
</form>
{% endblock %}

deposit/templates/deposit/preferences_nav.html
{% load i18n %}

<h2>{% trans "Preferences" %}</h2>

<ul class="nav nav-tabs">
  <li role="presentation" {% if not repository %}class="active"{% endif %}>
	<a href="{% url 'edit-global-preferences' %}">{% trans "General" %}</a></li>
  {% for repo in repositories %}
	{% if repo.get_implementation.preferences_model %}
	   <li role="presentation" {% if repository == repo %}class="active"{%endif%}>
		<a href="{% url 'edit-repo-preferences' repo.pk %}">{{ repo }}</a></li>
        {% endif %}
  {% endfor %}
</ul>

deposit/templates/deposit/repo_preferences.html
{% extends "dissemin/skeleton.html" %}

{% load i18n %}
{% load crispy_forms_tags %}


{% block extra_head %}
{% include 'statistics/headers.html' %}
<!-- repository-specific JS and CSS -->
{{ preferences_form.media }}
{% endblock %}

{% block headTitle %}{% trans "Repository preferences" %}{% endblock %}

{% block content %}
<div id="fullPage">

{% include "deposit/preferences_nav.html" %}
 
<form method="POST" action="{% url 'edit-repo-preferences' repository.id %}"
	id="repositoryPreferencesForm">
	{% crispy preferences_form  %}
</form>
{% endblock %}